#!/bin/bash

if [ "$1" = "" ]; then
   echo "usage: $0 root_directory"
   exit 1
fi

function move_to_devel()
{
   while [ "$1" != "" ]; do
      SOURCE="$(readlink -f $1)"
      DESTINATION="../06-devel/$1"

      if [ "$(echo $SOURCE | grep devel)" = "" ]; then
         mkdir -p "$(dirname $DESTINATION)"
         cp -af $SOURCE "$(dirname $DESTINATION)"
         rm -Rf "$SOURCE"

         if [ -d "$DESTINATION" ]; then
            mkdir -p "$SOURCE"
         fi
      fi
   shift
   done
}

function zip_recompress()
{
   local ZIP CWD TMPDIR

   ZIP="$(realpath "$1")"
   CWD="$(pwd)"
   TMPDIR=/tmp/zip-recompress

   rm -Rf "$TMPDIR"
   mkdir "$TMPDIR"
   cd "$TMPDIR"
   unzip "$ZIP"
   zip -0 -r new.zip *
   cat new.zip > "$ZIP" # this preserves attributes
   rm -Rf "$TMPDIR"
   cd "$CWD"
}


CWD=$(pwd)

cd "$1"

find -name ".wh.*" | xargs rm -Rf
rm -f boot/*
rm -f dev/*
rmdir mnt/*
rmdir media/*
rm -f media/*
rm -f mnt/README

rm -Rf usr/doc/*
rm -Rf usr/man/{?????,??,??_??}
rm -Rf {var,usr}/man/cat* usr/local/man/cat* # NOCACHE
rm -f usr/man/man{2,3,4,6,9}/*
rm -f usr/man/man1/perl?*
rm -f usr/man/* # all files and links but no directories
rm -f usr/info/*

rm -Rf usr/share/gtk-doc/*

# Unzip gzipped man pages, so LZMA can compress 2times better.
# First we gunzip symlinks, which will be overwritten by the content of targets
# this doesn't matter as mksquashfs will handle duplicate files correctly
find usr/man -type l -name "*.gz" | xargs gunzip -f
find usr/man -name "*.gz" | xargs gunzip

# remove locales (translated output of commandline programs)
find usr/share/locale -name "*.mo" | xargs -r rm
find usr/share/locale -name "man" | xargs -r rm
find usr/share/locale -name "LC_MESSAGES" | xargs -r rmdir
find usr/share/locale | xargs -r rmdir
find usr/lib{64,}/locale/ -maxdepth 1 | grep -v en_US.utf8 | xargs -r rm -Rf

# remove files with broken dependencies
rm usr/bin/alsaloop
rm usr/bin/cifscreds
rm usr/bin/getcifsacl
rm usr/bin/setcifsacl
rm usr/bin/wpa_gui
rm usr/lib*/alsa-lib/smixer/smixer-python.so
rm usr/lib/libcurl*
rm usr/lib/libldap*

# KDE
rm -Rf usr/share/apps/ksplash/Themes/Horos
ln -sf Minimalistic usr/share/apps/ksplash/Themes/Horos
#rm usr/share/apps/kdm/sessions/*
#rm -Rf usr/share/apps/kdm/themes/*
rm usr/share/apps/kdeui/about/body-background.jpg

# recompress zip archives
find | xargs file | grep "Zip archive data" | cut -d ":" -f 1 | while read ZIP; do
   echo Recompressing ZIP: $ZIP
   zip_recompress $ZIP
done

rm -Rf usr/share/zenmap/locale/*
rm -Rf usr/share/zenmap/docs/*
rm -Rf usr/share/zenmap/pixmaps/*

rm -f usr/share/sounds/alsa/*
rm -f usr/share/mc/help/mc.hlp.*
echo "[main]" > usr/share/mc/help/mc.hlp
rm -f usr/share/ncat/ca-bundle.crt

find usr/share/groff/current/font/ -maxdepth 1 | grep dev | grep -v devlatin1 | while read LINE; do
   rm -Rf "$LINE"
   ln -s devlatin1 "$LINE"
done

move_to_devel usr/include
move_to_devel $(find -name "*.h")
move_to_devel $(find -name "*.a")

find | xargs file | grep "not stripped" | cut -d : -f 1 | xargs -r strip --strip-unneeded
find -type f -name "*.a" | xargs -r strip --strip-unneeded

cd "$CWD"
